name: flutter_colorpicker
description: A HSV(HSB)/HSL color picker inspired by chrome devtools and a material color picker for your flutter app.
version: 0.3.5
homepage: https://github.com/mchome/flutter_colorpicker

dependencies:
  flutter:
    sdk: flutter

environment:
  sdk: ">=2.7.0 <3.0.0"